spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show.sql=true

server.port=8084


jwt.secret=yfB4b0YqcnYJhc1+bwx8t0ZMb22KD0rVlUPxrkCgJOo=