spring.application.name=query_service

#Jpa Properties
spring.datasource.url=jdbc:postgresql://localhost:5432/eventdb
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#redis Properties
spring.data.redis.host=localhost
spring.data.redis.port=6379

server.port=8083

jwt.secret=yfB4b0YqcnYJhc1+bwx8t0ZMb22KD0rVlUPxrkCgJOo=