spring.application.name=query_service

#Jpa Properties
spring.datasource.url=jdbc:postgresql://event-db:5432/eventdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#redis Properties
spring.data.redis.host=redis
spring.data.redis.port=6379

server.port=8083
